<h1 class='text-center'>List of all items in menu</h1>
<div class='row mt-5'>
    <?php
    $data = json_decode($data, true);
    foreach ($data as $value) {
        echo "<div class=\"card border-primary mb-3 mx-3\" style=\"max-width: 18rem;\">
        <div class=\"card-header bg-transparent border-primary\">$value[name]</div>
        <div class=\"card-body text-success\">
            <p class=\"card-text\"><strong class = 'text-black'>Cuisine : </strong>$value[cuisine]</p>
            <p class=\"card-text\"><strong class = 'text-black'>Price : </strong>$value[price]</p>
            <p class=\"card-text\"><strong class = 'text-black'>Restaurant ID : </strong>$value[restID]</p>
        </div>
        <div class=\"card-footer bg-transparent border-success\">
            <a href='/users/order?id=$value[itemID]' class = 'btn btn-success'>Order Now</a>
        </div>
        </div>";
    }
    ?>
</div>
<h3 class = 'mt-3 text-center'>Find by Cuisine</h3>
<?php
    $cuisine = json_decode($cuisine, true);
    foreach ($cuisine as $value) {
        echo "<a href='/users/cuisine?cuisine=$value' class = 'btn btn-info mx-3 my-5'>$value</a>";
    }
?>
